alias aptup='sudo apt update && sudo apt upgrade'
alias aptin='sudo apt install'
alias aptrm='sudo apt remove'
alias .1='cd ..'
alias .2='cd ../..'
alias web='cd ~/Desktop/git/govindchari.github.io && code .'
